#16 調整總表 UI
wanlong-church/service pull request #17
Opened 2024-03-02 14:03 UTC by lowkingshih

close #16 總表 UI 調整

## api  接口
1. sheetData 按照時間順序排列、去除多餘的欄位
## 總表 UI
1. 以年做區隔
2. 第一次進入頁面時自動開啟當週服事
3. 第一次進入頁面時滾動至當週服事
4. 總表顯示名稱由「Dashboard」改為「服事總表」
## 其他
1. 去除 safari hack，改用 100vh

2024-03-11 13:20 UTC, schwannden requested changes

2024-03-11 13:20 UTC, schwannden commented on app/(auth)/dashboard/sheet-view.tsx
> +		<Box id={`sheetAccordionItem_${date.getTime()}`}>
把這個id的function取出來吧，因為她跟前面為了scroll margin所使用的搜尋函數是同一個東西

2024-03-11 13:20 UTC, schwannden commented on app/(auth)/dashboard/sheet-view.tsx
> +		const elementId = thisWeekService ? `sheetAccordionItem_${new Date(thisWeekService.date).getTime()}` : '';
因為 thisWeekService 判斷已經保證有資料了，感覺是不是可以直接

```
const elementId = `sheetAccordionItem_${new Date(thisWeekService.date).getTime()}`;
```

2024-04-16 00:40 UTC, lowkingshih commented on app/(auth)/dashboard/page.tsx
> +	const sheetDataPromise = fetchGoogleSheetData();
挪到外層是希望 SheetView 專心渲染畫面，由外層取得資料，未來加上 PWA, cache 的邏輯也會寫在外層。

還有一個原因是 SheetView 裡有用到 React.use 這個 hook，如果有非同步的操作可以在上一層用 Suspense(原生 React 組件) 包住，做到 lazy loading 的效果。

否則就要在 SheetView 裡多一些 loading 等等的狀態。

2024-04-16 00:44 UTC, lowkingshih commented on app/(auth)/dashboard/sheet-view.tsx
> +		const elementId = thisWeekService ? `sheetAccordionItem_${new Date(thisWeekService.date).getTime()}` : '';
沒錯

2024-04-17 06:41 UTC, schwannden approved these changes

2024-04-17 07:01 UTC, merged