feat(ui): service table rwd
wanlong-church/service pull request #86
Opened 2024-09-21 16:10 UTC by lowkingshih

close #65

2024-09-24 01:02 UTC, schwannden requested changes

2024-09-24 01:02 UTC, schwannden commented on app/service/_components/monthly-accordion-item.tsx
> +  const thisWeekDate = rows.find((row) => {
如果這個是專門給mobile view用的話，要不要放進mobile view table?

2024-09-24 01:02 UTC, schwannden commented on app/service/_components/service-table/mobile.tsx
> +      uniqueDates.some(
default date已經從row.date找出來了，為什麼這邊需要再match一次？

2024-10-02 12:39 UTC, lowkingshih commented on app/service/_components/all-service-view.tsx
> +      date: isValid(date) ? format(date, 'yyyy/MM/dd') : row.date,
It would be more reasonable to move this logic to the display component in order to improve the appearance of the date.

2024-10-03 02:50 UTC, schwannden requested changes

2024-10-03 02:50 UTC, schwannden commented on app/service/_components/service-table/mobile.tsx
> +import { addDays, format, startOfWeek } from 'date-fns'
format is unused

2024-10-03 03:18 UTC, schwannden approved these changes
Nicely done! Love the new look!

2024-10-03 03:19 UTC, merged